import json
from unittest.mock import patch

from rest_api.rest_api_server.tests.unittests.test_api_base import TestApiBase


class TestSsoOidcApi(TestApiBase):

    def setUp(self, version='v2'):
        super().setUp(version)
        _, self.organization = self.client.organization_create(
            {'name': 'sso-org'})
        self.org_id = self.organization['id']
        self.sso_payload = {
            'enabled': True,
            'issuer': 'https://example.onelogin.com/oidc/2',
            'client_id': 'cid',
            'client_secret': 'super-secret',
            'authorization_endpoint': '',
            'login_only': True,
        }

    def _save_sso(self, payload=None, org_id=None):
        value = {'value': json.dumps(payload or self.sso_payload)}
        return self.client.organization_option_create(
            org_id or self.org_id, 'sso_oidc', value)

    def test_public_config_empty(self):
        code, resp = self.client.sso_login_config_get()
        self.assertEqual(code, 200)
        self.assertFalse(resp['configured'])
        self.assertFalse(resp['enabled'])
        self.assertNotIn('client_secret', resp)

    def test_public_config_omits_secret(self):
        code, _ = self._save_sso()
        self.assertEqual(code, 200)
        secret = self.client.secret
        self.client.secret = ''
        code, resp = self.client.sso_login_config_get()
        self.client.secret = secret
        self.assertEqual(code, 200)
        self.assertTrue(resp['configured'])
        self.assertTrue(resp['enabled'])
        self.assertEqual(resp['issuer'], self.sso_payload['issuer'])
        self.assertEqual(resp['client_id'], 'cid')
        self.assertTrue(resp['login_only'])
        self.assertNotIn('client_secret', resp)

    def test_public_config_include_secret_with_cluster_secret(self):
        self._save_sso()
        code, resp = self.client.sso_login_config_get(include_secret=True)
        self.assertEqual(code, 200)
        self.assertEqual(resp['client_secret'], 'super-secret')

    def test_public_config_include_secret_without_cluster_secret(self):
        self._save_sso()
        secret = self.client.secret
        self.client.secret = ''
        code, resp = self.client.sso_login_config_get(include_secret=True)
        self.client.secret = secret
        self.assertEqual(code, 200)
        self.assertNotIn('client_secret', resp)

    def test_option_get_redacts_secret(self):
        self._save_sso()
        patch(
            'rest_api.rest_api_server.handlers.v2.organization_options.'
            'OrganizationOptionsAsyncItemHandler.check_cluster_secret',
            return_value=False).start()
        code, resp = self.client.organization_option_get(
            self.org_id, 'sso_oidc')
        self.assertEqual(code, 200)
        value = json.loads(resp['value'])
        self.assertNotIn('client_secret', value)
        self.assertTrue(value['has_client_secret'])
        self.assertEqual(value['client_id'], 'cid')

    def test_empty_secret_keeps_previous(self):
        self._save_sso()
        updated = dict(self.sso_payload)
        updated['client_secret'] = ''
        updated['login_only'] = False
        code, resp = self._save_sso(updated)
        self.assertEqual(code, 200)
        code, secret_resp = self.client.sso_login_config_get(
            include_secret=True)
        self.assertEqual(code, 200)
        self.assertEqual(secret_resp['client_secret'], 'super-secret')
        self.assertFalse(secret_resp['login_only'])

    def test_enabled_requires_issuer(self):
        code, resp = self._save_sso({
            'enabled': True,
            'issuer': '',
            'client_id': 'cid',
            'client_secret': 'secret',
        })
        self.assertEqual(code, 400)
        self.assertEqual(resp['error']['error_code'], 'OE0216')

    @patch('rest_api.rest_api_server.handlers.v2.organizations.'
           'OrganizationAsyncCollectionHandler.check_cluster_secret',
           return_value=False)
    def test_sso_auto_join_on_org_list(self, _p_secret):
        self._save_sso()
        new_user = self.gen_id()
        self.p_get_user_info.return_value = {
            'id': new_user,
            'display_name': 'SSO User',
            'email': 'sso@example.com',
            'is_password_autogenerated': True,
        }
        patch(
            'rest_api.rest_api_server.controllers.organization.'
            'OrganizationController._get_assignments_by_token',
            return_value=[]).start()
        p_assign = patch(
            'rest_api.rest_api_server.controllers.organization.'
            'OrganizationController.assign_role_to_user').start()
        code, _resp = self.client.organization_list()
        self.assertEqual(code, 200)
        p_assign.assert_called_once()
        self.assertEqual(p_assign.call_args[0][0], new_user)
        self.assertEqual(p_assign.call_args[0][1], self.org_id)
        code, employees = self.client.employee_list(self.org_id)
        self.assertEqual(code, 200)
        auth_ids = [item['auth_user_id'] for item in employees['employees']]
        self.assertIn(new_user, auth_ids)

    @patch('rest_api.rest_api_server.handlers.v2.organizations.'
           'OrganizationAsyncCollectionHandler.check_cluster_secret',
           return_value=False)
    def test_no_auto_join_when_sso_disabled(self, _p_secret):
        disabled = dict(self.sso_payload)
        disabled['enabled'] = False
        self._save_sso(disabled)
        patch(
            'rest_api.rest_api_server.controllers.organization.'
            'OrganizationController._get_assignments_by_token',
            return_value=[]).start()
        p_assign = patch(
            'rest_api.rest_api_server.controllers.organization.'
            'OrganizationController.assign_role_to_user').start()
        code, resp = self.client.organization_list()
        self.assertEqual(code, 200)
        self.assertEqual(resp['organizations'], [])
        p_assign.assert_not_called()
