SELECT 'DATA_TRANSFER_HISTORY' AS view_name,
       COUNT(*) AS row_count_30d
FROM SNOWFLAKE.ACCOUNT_USAGE.DATA_TRANSFER_HISTORY
WHERE start_time >= DATEADD(day, -30, CURRENT_TIMESTAMP())
UNION ALL
SELECT 'LISTING_CONSUMPTION_DAILY',
       COUNT(*)
FROM SNOWFLAKE.DATA_SHARING_USAGE.LISTING_CONSUMPTION_DAILY
WHERE event_date >= DATEADD(day, -30, CURRENT_DATE())
UNION ALL
SELECT 'MARKETPLACE_PAID_USAGE_DAILY',
       COUNT(*)
FROM SNOWFLAKE.DATA_SHARING_USAGE.MARKETPLACE_PAID_USAGE_DAILY
WHERE usage_date >= DATEADD(day, -30, CURRENT_DATE())
UNION ALL
SELECT 'READER_WAREHOUSE_METERING_HISTORY',
       COUNT(*)
FROM SNOWFLAKE.READER_ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE start_time >= DATEADD(day, -30, CURRENT_TIMESTAMP())
UNION ALL
SELECT 'METERING_DAILY_HISTORY (AI_INFERENCE)',
       COUNT(*)
FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_DAILY_HISTORY
WHERE service_type = 'AI_INFERENCE'
  AND usage_date >= DATEADD(day, -30, CURRENT_DATE())
