SELECT 'CORTEX_AI_FUNCTIONS_USAGE_HISTORY' AS view_name,
       COUNT(*) AS row_count_30d
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AI_FUNCTIONS_USAGE_HISTORY
WHERE start_time >= DATEADD(day, -30, CURRENT_TIMESTAMP())
UNION ALL
SELECT 'CORTEX_AGENT_USAGE_HISTORY',
       COUNT(*)
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AGENT_USAGE_HISTORY
WHERE start_time >= DATEADD(day, -30, CURRENT_TIMESTAMP())
UNION ALL
SELECT 'CORTEX_CODE_CLI_USAGE_HISTORY',
       COUNT(*)
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_CODE_CLI_USAGE_HISTORY
WHERE usage_time >= DATEADD(day, -30, CURRENT_TIMESTAMP())
UNION ALL
SELECT 'CORTEX_CODE_SNOWSIGHT_USAGE_HISTORY',
       COUNT(*)
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_CODE_SNOWSIGHT_USAGE_HISTORY
WHERE usage_time >= DATEADD(day, -30, CURRENT_TIMESTAMP())
UNION ALL
SELECT 'CORTEX_CODE_DESKTOP_USAGE_HISTORY',
       COUNT(*)
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_CODE_DESKTOP_USAGE_HISTORY
WHERE usage_time >= DATEADD(day, -30, CURRENT_TIMESTAMP())
UNION ALL
SELECT 'SNOWFLAKE_INTELLIGENCE_USAGE_HISTORY',
       COUNT(*)
FROM SNOWFLAKE.ACCOUNT_USAGE.SNOWFLAKE_INTELLIGENCE_USAGE_HISTORY
WHERE start_time >= DATEADD(day, -30, CURRENT_TIMESTAMP())
