SELECT 'CORTEX_AI_FUNCTIONS' AS source,
       SUM(credits) AS total_credits,
       COUNT(*) AS rows
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AI_FUNCTIONS_USAGE_HISTORY
WHERE start_time >= DATEADD(day, -7, CURRENT_TIMESTAMP())
  AND start_time < CURRENT_TIMESTAMP()
UNION ALL
SELECT 'CORTEX_AGENTS',
       SUM(token_credits),
       COUNT(*)
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_AGENT_USAGE_HISTORY
WHERE start_time >= DATEADD(day, -7, CURRENT_TIMESTAMP())
  AND start_time < CURRENT_TIMESTAMP()
UNION ALL
SELECT 'CORTEX_CODE_CLI',
       SUM(token_credits),
       COUNT(*)
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_CODE_CLI_USAGE_HISTORY
WHERE usage_time >= DATEADD(day, -7, CURRENT_TIMESTAMP())
  AND usage_time < CURRENT_TIMESTAMP()
UNION ALL
SELECT 'CORTEX_CODE_SNOWSIGHT',
       SUM(token_credits),
       COUNT(*)
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_CODE_SNOWSIGHT_USAGE_HISTORY
WHERE usage_time >= DATEADD(day, -7, CURRENT_TIMESTAMP())
  AND usage_time < CURRENT_TIMESTAMP()
UNION ALL
SELECT 'CORTEX_CODE_DESKTOP',
       SUM(token_credits),
       COUNT(*)
FROM SNOWFLAKE.ACCOUNT_USAGE.CORTEX_CODE_DESKTOP_USAGE_HISTORY
WHERE usage_time >= DATEADD(day, -7, CURRENT_TIMESTAMP())
  AND usage_time < CURRENT_TIMESTAMP()
UNION ALL
SELECT 'SNOWFLAKE_INTELLIGENCE',
       SUM(token_credits),
       COUNT(*)
FROM SNOWFLAKE.ACCOUNT_USAGE.SNOWFLAKE_INTELLIGENCE_USAGE_HISTORY
WHERE start_time >= DATEADD(day, -7, CURRENT_TIMESTAMP())
  AND start_time < CURRENT_TIMESTAMP()
