SELECT 'DATA_TRANSFER (bytes)' AS source,
       NULL AS total_credits,
       SUM(bytes_transferred) AS total_bytes,
       COUNT(*) AS rows
FROM SNOWFLAKE.ACCOUNT_USAGE.DATA_TRANSFER_HISTORY
WHERE start_time >= DATEADD(day, -7, CURRENT_TIMESTAMP())
  AND start_time < CURRENT_TIMESTAMP()
UNION ALL
SELECT 'READER_WAREHOUSE (credits)',
       SUM(credits_used),
       NULL,
       COUNT(*)
FROM SNOWFLAKE.READER_ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE start_time >= DATEADD(day, -7, CURRENT_TIMESTAMP())
  AND start_time < CURRENT_TIMESTAMP()
UNION ALL
SELECT 'MARKETPLACE_PAID (charge)',
       SUM(charge),
       NULL,
       COUNT(*)
FROM SNOWFLAKE.DATA_SHARING_USAGE.MARKETPLACE_PAID_USAGE_DAILY
WHERE usage_date >= DATEADD(day, -7, CURRENT_DATE())
  AND usage_date < CURRENT_DATE()
UNION ALL
SELECT 'LISTING_CONSUMPTION (jobs)',
       NULL,
       NULL,
       SUM(jobs)
FROM SNOWFLAKE.DATA_SHARING_USAGE.LISTING_CONSUMPTION_DAILY
WHERE event_date >= DATEADD(day, -7, CURRENT_DATE())
  AND event_date < CURRENT_DATE()
